[package]
name = "imageconvert"
description = "An image converter from SPACESIM.EXE .R8 and .PLT files to modern .BMP files."
version = "0.1.0"
edition = "2024"

[dependencies]
bmp = "0.5.0"
clap = { version = "4.5.41", features = ["derive"] }
dataview = "~1.0"
